from classes import *
from adv import *
mkSYNON(15, ['OBJECT'])
OBJECT = 15
mkSYNON(14, ['VERB'])
VERB = 14
mkSYNON(13, ['PLACE'])
PLACE = 13
mkSYNON(12, ['BADWORD'])
BADWORD = 12
mkSYNON(0, ['MOVED'])
MOVED = 0
mkSYNON(1, ['QUICKIE'])
QUICKIE = 1
mkSYNON(2, ['FASTMODE'])
FASTMODE = 2
mkSYNON(3, ['FULLDISP'])
FULLDISP = 3
mkSYNON(0, ['LIT'])
LIT = 0
mkSYNON(1, ['BEENHERE'])
BEENHERE = 1
mkSYNON(2, ['NODWARF'])
NODWARF = 2
mkSYNON(3, ['NOBACK'])
NOBACK = 3
mkSYNON(4, ['NOTINCAVE'])
NOTINCAVE = 4
mkSYNON(5, ['HINTABLE'])
HINTABLE = 5
mkSYNON(6, ['H20HERE'])
H20HERE = 6
mkSYNON(7, ['INMAZE'])
INMAZE = 7
mkSYNON(8, ['ONE_EXIT'])
ONE_EXIT = 8
mkSYNON(9, ['THROWER'])
THROWER = 9
mkSYNON(0, ['PORTABLE'])
PORTABLE = 0
mkSYNON(1, ['SEEN'])
SEEN = 1
mkSYNON(2, ['VALUED'])
VALUED = 2
mkSYNON(3, ['SCHIZOID'])
SCHIZOID = 3
mkSYNON(4, ['UNSTABLE'])
UNSTABLE = 4
mkSYNON(5, ['MORTAL'])
MORTAL = 5
mkSYNON(6, ['OPENABLE'])
OPENABLE = 6
mkSYNON(7, ['INVISIBLE'])
INVISIBLE = 7
mkSYNON(8, ['EDIBLE'])
EDIBLE = 8
mkSYNON(9, ['FREEBIE'])
FREEBIE = 9
mkSYNON(10, ['SPECIAL1'])
SPECIAL1 = 10
mkSYNON(11, ['SPECIAL2'])
SPECIAL2 = 11
mkSYNON(0, ['DEMO'])
DEMO = 0
mkSYNON(1, ['TICKER'])
TICKER = 1
mkSYNON(3, ['NOMAGIC'])
NOMAGIC = 3
mkSYNON(4, ['PANICED'])
PANICED = 4
mkSYNON(5, ['OLORIN'])
OLORIN = 5
mkSYNON(6, ['RANOUT'])
RANOUT = 6
mkSYNON(30, ['MINTIME'])
MINTIME = 30
mkSYNON(30, ['MAX_DEMO'])
MAX_DEMO = 30
mkSYNON(600, ['MAX_GAME'])
MAX_GAME = 600
mkSYNON(20, ['HINT_COST'])
HINT_COST = 20
mkSYNON(20, ['CLOSE_CREDIT'])
CLOSE_CREDIT = 20
HERE = VARIABLE('HERE')
THERE = VARIABLE('THERE')
ARG1 = VARIABLE('ARG1')
ARG2 = VARIABLE('ARG2')
STATUS = VARIABLE('STATUS')
LAMPLIFE = VARIABLE('LAMPLIFE')
I = VARIABLE('I')
J = VARIABLE('J')
K = VARIABLE('K')
L = VARIABLE('L')
INVCT = VARIABLE('INVCT')
DEATHS = VARIABLE('DEATHS')
PENALTIES = VARIABLE('PENALTIES')
SCOREX = VARIABLE('SCOREX')
MAXSCORE = VARIABLE('MAXSCORE')
TURNS = VARIABLE('TURNS')
ADMIN = VARIABLE('ADMIN')
MOVES = VARIABLE('MOVES')
FOOBAR = VARIABLE('FOOBAR')
DWARFCOUNT = VARIABLE('DWARFCOUNT')
CLOCK = VARIABLE('CLOCK')
CLOSURE = VARIABLE('CLOSURE')
QUITTING = VARIABLE('QUITTING')
OK = VARIABLE('OK')
TIME = VARIABLE('TIME')
HINT_TIME = VARIABLE('HINT_TIME')
STRENGTH = VARIABLE('STRENGTH')
MUSHTIME = VARIABLE('MUSHTIME')
DRAGTIME = VARIABLE('DRAGTIME')
LASTCLOCK = VARIABLE('LASTCLOCK')
PASSWORD = VARIABLE('PASSWORD')
DWARROWS = VARIABLE('DWARROWS')
SAFEEXIT = VARIABLE('SAFEEXIT')
ESCAPE = VARIABLE('ESCAPE')
CAMEO_TIME = VARIABLE('CAMEO_TIME')
